#!/usr/bin/env python3
"""Compact a feature's Pencil HTML exports so builds read a fraction of the bytes.

Exports are one full page per state, so a screen with 17 states repeats the same
markup 17 times, and over half of each file is icon SVG paths. For each screen and
device this writes, into docs/features/<slug>/exports/_compact/:

  <screen>-<device>.base.html     the most typical state, SVG bodies and <head> removed
  <screen>-<device>.<state>.diff  every other state as a unified diff against the base
  INDEX.md                        screen, device, base, states, sizes

The raw exports stay untouched and remain the source of truth; open one only for
exact icon paths. Run after (re-)exporting a design:

    python3 scripts/sdv/compact-exports.py <slug>          # write
    python3 scripts/sdv/compact-exports.py <slug> --check  # exit 1 if out of date
"""
import difflib
import re
import shutil
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NAME = re.compile(r"^(?P<state>.+?)(?:-(?P<device>desktop|mobile|tablet))?-(?P<frame>[A-Za-z0-9]{5,})\.html$")


def normalize(path):
    text = path.read_text()
    body = text[text.index("<body"):] if "<body" in text else text
    # keep each <svg ...> opening tag (size, classes) and drop its paths
    body = re.sub(r"(<svg\b[^>]*>).*?</svg>", r"\1</svg>", body, flags=re.S)
    body = re.sub(r">\s*<", ">\n<", body)
    return [line.rstrip() for line in body.split("\n") if line.strip()]


def diff_lines(base, other):
    return list(difflib.unified_diff(base, other, "base", "state", lineterm="", n=2))


def pick_base(lines_by_state):
    """The state that differs least from the others, so the diffs stay small."""
    if len(lines_by_state) == 1:
        return next(iter(lines_by_state))
    best, best_cost = None, None
    for cand, cl in lines_by_state.items():
        cost = sum(
            sum(len(l) for l in diff_lines(cl, ol) if l[:1] in "+-")
            for other, ol in lines_by_state.items()
            if other != cand
        )
        if best_cost is None or cost < best_cost:
            best, best_cost = cand, cost
    return best


def build(slug):
    src = ROOT / "docs" / "features" / slug / "exports"
    if not src.is_dir():
        sys.exit(f"no exports folder: {src.relative_to(ROOT)}")
    groups = defaultdict(dict)
    raw_size = {}
    for f in sorted(src.glob("*.html")):
        m = NAME.match(f.name)
        if not m:
            print(f"skipped (unrecognised name): {f.name}", file=sys.stderr)
            continue
        state, device = m["state"], m["device"] or "any"
        screen = state.split("-")[0]
        groups[(screen, device)][state] = f
        raw_size[f] = f.stat().st_size

    out = {}
    index = [
        f"# Compact exports — {slug}",
        "",
        "<!-- generated by scripts/sdv/compact-exports.py; do not edit -->",
        "",
        "Read the **base** once per screen and device, then only the diffs for the states you need. "
        "A diff is `diff -u` against the base (`-` removed, `+` added). Open a raw export in `../` only for exact icon paths.",
        "",
    ]
    total_raw = total_out = 0
    for (screen, device), states in sorted(groups.items()):
        lines = {s: normalize(f) for s, f in states.items()}
        base = pick_base(lines)
        base_name = f"{screen}-{device}.base.html"
        out[base_name] = "\n".join(lines[base]) + "\n"
        rows = [f"| `{base}` (base) | [{base_name}]({base_name}) | {len(out[base_name]) // 1000} KB | {raw_size[states[base]] // 1000} KB |"]
        total_raw += raw_size[states[base]]
        total_out += len(out[base_name])
        for state in sorted(states):
            if state == base:
                continue
            d = diff_lines(lines[base], lines[state])
            name = f"{screen}-{device}.{state}.diff"
            out[name] = ("\n".join(d) + "\n") if d else "(identical to base)\n"
            rows.append(f"| `{state}` | [{name}]({name}) | {len(out[name]) // 1000} KB | {raw_size[states[state]] // 1000} KB |")
            total_raw += raw_size[states[state]]
            total_out += len(out[name])
        index += [f"## {screen} / {device}", "", "| State | File | Compact | Raw |", "|---|---|---|---|", *rows, ""]
    index.insert(5, f"Total: {total_raw // 1000} KB raw → {total_out // 1000} KB compact.")
    index.insert(6, "")
    out["INDEX.md"] = "\n".join(index)
    return src / "_compact", out, total_raw, total_out


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    if len(args) != 1:
        sys.exit(__doc__)
    dst, out, raw, compact = build(args[0])
    stale = [n for n, c in out.items() if not (dst / n).exists() or (dst / n).read_text() != c]
    orphans = [p.name for p in dst.glob("*") if p.name not in out] if dst.is_dir() else []
    if "--check" in sys.argv:
        for n in stale + orphans:
            print(f"out of date: {n}")
        sys.exit(1 if stale or orphans else 0)
    if dst.is_dir():
        shutil.rmtree(dst)
    dst.mkdir(parents=True)
    for n, c in out.items():
        (dst / n).write_text(c)
    print(f"{len(out) - 1} files in {dst.relative_to(ROOT)}: {raw // 1000} KB raw -> {compact // 1000} KB compact")


main()
