#!/usr/bin/env python3
"""Write docs/features/<slug>/exports/INDEX.md: a table of a feature's raw Pencil HTML exports.

Builds read the raw exports (one complete frame per file), so this index exists to find
the right file for each state without listing the folder. The index groups the exports
by screen. Each state gets a row with its desktop and mobile files, their sizes, and,
when design.md lists the frame ID, the state description and the AC from design.md.

Export file names follow `<screen>-<state>-<device>-<frameId>.html`. Exports may sit in
subfolders (one per flow group); the index then groups rows by subfolder instead of by
screen and links each file by its relative path. Run after
(re-)exporting a design:

    python3 scripts/sdv/index-exports.py <slug>          # write
    python3 scripts/sdv/index-exports.py <slug> --check  # exit 1 if out of date
"""
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NAME = re.compile(r"^(?P<state>.+?)-(?P<device>desktop|mobile|tablet)-(?P<frame>[A-Za-z0-9]{4,})\.html$")
ROW = re.compile(r"^\|(?P<label>[^|]+)\|(?P<cells>.*)\|\s*$")
FRAME_ID = re.compile(r"`([A-Za-z0-9]{4,})`")
DEVICES = ("desktop", "tablet", "mobile")


def design_notes(design):
    """Map each frame ID in design.md's tables to (state description, AC)."""
    notes = {}
    if not design.exists():
        return notes
    for line in design.read_text().splitlines():
        match = ROW.match(line)
        if not match:
            continue
        cells = [c.strip() for c in match["cells"].split("|")]
        ac = cells[-1] if cells and re.search(r"\b(AC-[A-Z]+-\d|C-\d)", cells[-1]) else ""
        for cell in cells:
            for frame in FRAME_ID.findall(cell):
                notes[frame] = (match["label"].strip(), ac)
    return notes


def render(slug):
    folder = ROOT / "docs" / "features" / slug / "exports"
    notes = design_notes(folder.parent / "design.md")
    states = defaultdict(dict)
    unmatched = []
    groups = {}
    for path in sorted(folder.rglob("*.html")):
        rel = path.relative_to(folder).as_posix()
        match = NAME.match(path.name)
        if not match:
            unmatched.append(rel)
            continue
        group = rel.rsplit("/", 1)[0] if "/" in rel else match["state"].split("-", 1)[0]
        key = (group, match["state"])
        groups[key] = group
        states[key][match["device"]] = (rel, match["frame"], path.stat().st_size)
    screens = defaultdict(list)
    for key in sorted(states):
        screens[groups[key]].append(key)
    devices = [d for d in DEVICES if any(d in files for files in states.values())]
    out = [
        f"# Exports — {slug}",
        "",
        "<!-- generated by scripts/sdv/index-exports.py; do not edit -->",
        "",
        "Raw Pencil HTML exports, one complete frame per file. Read only the states your task names,",
        "one file at a time. *Design note* and *AC* come from [design.md](../design.md).",
        f"Total: {sum(len(f) for f in states.values())} files, "
        f"{sum(s for f in states.values() for _, _, s in f.values()) // 1024} KB.",
    ]
    for screen, names in screens.items():
        out += ["", f"## {screen}", ""]
        out.append("| State | " + " | ".join(d.capitalize() for d in devices) + " | Design note | AC |")
        out.append("|---|" + "---|" * len(devices) + "---|---|")
        for state in names:
            files = states[state]
            cells = []
            note = ("", "")
            for device in devices:
                if device not in files:
                    cells.append("—")
                    continue
                name, frame, size = files[device]
                cells.append(f"[`{frame}`]({name}) · {size // 1024} KB")
                note = notes.get(frame, note) if not note[0] else note
            out.append(f"| `{state[1]}` | " + " | ".join(cells) + f" | {note[0]} | {note[1]} |")
    if unmatched:
        out += ["", "## Not matched", "", "File names that don't follow `<screen>-<state>-<device>-<frameId>.html`:", ""]
        out += [f"- `{name}`" for name in unmatched]
    return folder / "INDEX.md", "\n".join(out) + "\n"


def main(argv):
    if not argv or argv[0].startswith("-"):
        sys.exit("usage: index-exports.py <slug> [--check]")
    target, text = render(argv[0])
    if "--check" in argv:
        if not target.exists() or target.read_text() != text:
            sys.exit(f"{target.relative_to(ROOT)} is out of date; run index-exports.py {argv[0]}")
        print("index up to date")
        return
    target.write_text(text)
    print(f"wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main(sys.argv[1:])
