export const OWNER_NAV_COPY = {
  dashboard: "Dasbor",
  projects: "Proyek",
  clients: "Klien",
  invoices: "Invoice",
  services: "Layanan",
  team: "Tim",
  catalog: "KATALOG",
  messageTemplates: "Template pesan",
  clientSources: "Sumber klien",
  settings: "Pengaturan",
  create: "Proyek baru",
  search: "Pencarian",
  notifications: "Notifikasi",
  dashboardSubtitle: (workspaceName: string) => `Ringkasan workspace ${workspaceName}.`,
  settingsSubtitle: "Kelola identitas brand, kontak, dan invoice workspace.",
  comingSoonSubtitle: "Segera hadir.",
} as const;
