export const OWNER_NAV_COPY = {
  dashboard: "Dasbor",
  projects: "Proyek",
  projectsSubtitle: "Setiap pemotretan yang kamu pegang, dari draf sampai selesai.",
  projectsMobileSubtitle: "Pemotretan dari draf sampai selesai.",
  projectsTabsLabel: "Status proyek",
  projectTabs: { active: "Aktif", completed: "Selesai", cancelled: "Dibatalkan" },
  clients: "Klien",
  clientsSubtitle: "Orang yang memesan sesi foto. Pilih mereka saat membuat proyek.",
  clientsMobileSubtitle: "Orang yang memesan sesi foto.",
  clientsTabsLabel: "Status klien",
  clientTabs: { active: "Aktif", archived: "Arsip" },
  invoices: "Invoice",
  services: "Layanan",
  servicesSubtitle: "Paket yang kamu jual. Proyek baru menyalin isi paket saat dibuat.",
  servicesTabsLabel: "Bagian layanan",
  serviceTabs: { services: "Layanan", categories: "Kategori", items: "Item paket" },
  team: "Tim",
  teamSubtitle: "Freelancer yang kamu ajak bertugas. Pilih mereka di jadwal proyek.",
  teamMobileSubtitle: "Freelancer yang kamu ajak bertugas.",
  // not in Pencil: the tab bar's accessible name
  teamTabsLabel: "Bagian tim",
  teamTabs: { active: "Aktif", archived: "Arsip", roles: "Peran" },
  catalog: "KATALOG",
  messageTemplates: "Template pesan",
  photoSources: "Sumber foto",
  settings: "Pengaturan",
  create: "Proyek baru",
  search: "Pencarian",
  notifications: "Notifikasi",
  dashboardSubtitle: (workspaceName: string) => `Ringkasan workspace ${workspaceName}.`,
  settingsSubtitle: "Atur identitas brand, kontak, dan format invoice workspace ini.",
  messageTemplatesSubtitle:
    "Pesan WhatsApp untuk klien. Kamu tetap mengirimnya sendiri dari WhatsApp.",
  photoSourcesSubtitle:
    "Tempat foto gallery-mu disimpan. Shutrly hanya membaca, tidak pernah mengubah isinya.",
  comingSoonSubtitle: "Segera hadir.",
} as const;
