import type { ClientStatus } from "@/features/booking/domain/client-list/client-list.types";

export const PLATFORM_COPY = {
  INSTAGRAM: "Instagram",
  TIKTOK: "TikTok",
  FACEBOOK: "Facebook",
  YOUTUBE: "YouTube",
  X: "X",
  OTHER: "Lainnya",
} as const;
export const CLIENT_COPY = {
  listTitle: "Daftar klien",
  searchLabel: "Cari klien",
  searchPlaceholder: "Cari nama atau nomor WhatsApp",
  clearSearch: "Hapus pencarian",
  searchResultCount: (count: number) => `${String(count)} klien cocok`,
  noMatchTitle: "Tidak ada klien yang cocok",
  noMatchBody: "Coba nama lain, atau ketik sebagian nomor WhatsApp.",
  loadMore: "Muat lebih banyak",
  loadingMore: "Memuat…",
  noWhatsapp: "Belum ada nomor WhatsApp",
  noSocialLinks: "—",
  tabsLabel: "Status klien",
  active: "Aktif",
  archived: "Arsip",
  add: "Tambah",
  addClient: "Tambah klien",
  edit: "Ubah",
  openWhatsapp: "Buka WhatsApp",
  archive: "Arsipkan",
  restore: "Pulihkan",
  delete: "Hapus",
  deleteClient: "Hapus klien",
  deleting: "Menghapus…",
  close: "Tutup",
  deleteTitle: (name: string) => `Hapus klien "${name}"?`,
  deleteDescription:
    "Nama, nomor WhatsApp, dan media sosialnya dihapus permanen. Nomornya bisa dipakai klien lain.",
  deleteBlockedTitle: "Klien ini punya proyek. Arsipkan saja.",
  deleteBlockedBody: (name: string) => `${name} tidak dihapus.`,
  rowActions: (name: string) => `Aksi untuk ${name}`,
  archivedTitle: "Klien diarsipkan",
  archivedBody: (name: string) => `${name} pindah ke Arsip.`,
  restoredTitle: "Klien dipulihkan",
  deletedTitle: "Klien dihapus",
  undo: "Batalkan",
  emptyActiveTitle: "Belum ada klien aktif",
  emptyActiveBody: "Tambahkan orang yang memesan sesi foto, lalu pilih mereka saat membuat proyek.",
  emptyArchivedTitle: "Belum ada klien di arsip",
  emptyArchivedBody: "Klien yang kamu arsipkan muncul di sini dan bisa dipulihkan kapan saja.",
  dialogTitle: "Tambah klien",
  dialogDescription: "Klien bisa dipilih saat membuat proyek.",
  editDialogTitle: "Ubah klien",
  editDialogDescription: "Perubahan dipakai di proyek dan pesan berikutnya.",
  name: "Nama klien",
  namePlaceholder: "Contoh: Rina Wedding",
  whatsappNumber: "Nomor WhatsApp",
  whatsappDescription: "Contoh: 0812 3456 7890. Nomor luar negeri diawali + dan kode negara.",
  socialLinks: "Media sosial",
  socialLinksOptional: "opsional",
  socialLinksLabel: "Media sosial (opsional)",
  socialValuePlaceholderDesktop: "@nama atau tautan https://",
  socialValuePlaceholderMobile: "@nama atau tautan",
  addSocialLink: "Tambah media sosial",
  removeSocialLink: "Hapus media sosial",
  socialPlatformField: (index: number) => `Platform media sosial ${String(index)}`,
  socialValueField: (platform: string, index: number) => `Akun ${platform} ${String(index)}`,
  removeSocialLinkField: (platform: string, index: number) => `Hapus ${platform} ${String(index)}`,
  cancel: "Batal",
  save: "Tambah klien",
  saveEdit: "Simpan",
  saving: "Menyimpan…",
  addedTitle: "Klien ditambahkan",
  addedBody: (name: string) => `${name} siap dipilih saat membuat proyek.`,
  savedTitle: "Perubahan disimpan",
  serverErrorTitle: "Perubahan belum tersimpan",
  serverErrorBody: "Terjadi kendala di server. Data klienmu tidak berubah.",
  retry: "Coba lagi",
  invalidWhatsapp: "Nomor WhatsApp tidak valid",
  emptySocialValue: "Isi akun atau tautan.",
  count: (status: ClientStatus, count: number) =>
    `${String(count)} klien ${status === "ACTIVE" ? "aktif" : "diarsipkan"}`,
} as const;
