type Json = Record<string, unknown>;
interface Leaf {
  path: string[];
  value: unknown;
  dark: unknown;
}
const HEADER =
  "/* Generated by `pnpm tokens:css` from docs/design-system/tokens.json. Do not edit. */";
const ALIAS = /^\{([^}]+)\}$/;
const UNITLESS_PREFIXES = ["opacity.", "font.line-height.", "font.weight."];
function isObject(value: unknown): value is Json {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
function collect(node: Json, path: string[], out: Leaf[]): void {
  if ("$value" in node) {
    const modes = isObject(node.$extensions) ? node.$extensions["dev.pen.modes"] : undefined;
    out.push({ path, value: node.$value, dark: isObject(modes) ? modes.dark : undefined });
    return;
  }
  for (const [key, child] of Object.entries(node))
    if (!key.startsWith("$") && isObject(child)) collect(child, [...path, key], out);
}
export function cssVarName(path: readonly string[]): string {
  return `--${path.join("-")}`;
}
function formatValue(dotted: string, raw: unknown, known: ReadonlySet<string>): string {
  if (typeof raw === "string") {
    const alias = ALIAS.exec(raw);
    if (alias) {
      const target = alias[1];
      if (!known.has(target)) throw new Error(`Unknown alias {${target}} in ${dotted}`);
      return `var(${cssVarName(target.split("."))})`;
    }
    return dotted.startsWith("font.family.") ? `"${raw}"` : raw;
  }
  if (typeof raw === "number")
    return UNITLESS_PREFIXES.some((prefix) => dotted.startsWith(prefix))
      ? String(raw)
      : `${String(raw)}px`;
  throw new Error(`Unsupported token value in ${dotted}`);
}
export function buildTokensCss(tokens: unknown): { css: string; count: number } {
  if (!isObject(tokens)) throw new Error("tokens.json must contain an object");
  const leaves: Leaf[] = [];
  collect(tokens, [], leaves);
  const known = new Set(leaves.map((leaf) => leaf.path.join(".")));
  const owners = new Map<string, string>();
  for (const leaf of leaves) {
    const name = cssVarName(leaf.path);
    const previous = owners.get(name);
    if (previous)
      throw new Error(`CSS variable collision ${name}: ${previous} and ${leaf.path.join(".")}`);
    owners.set(name, leaf.path.join("."));
  }
  const line = (leaf: Leaf, raw: unknown) =>
    `  ${cssVarName(leaf.path)}: ${formatValue(leaf.path.join("."), raw, known)};`;
  const css = [
    HEADER,
    ":root {",
    ...leaves.map((leaf) => line(leaf, leaf.value)),
    "}",
    "",
    '[data-theme="dark"] {',
    ...leaves.filter((leaf) => leaf.dark !== undefined).map((leaf) => line(leaf, leaf.dark)),
    "}",
    "",
    "",
  ].join("\n");
  return { css, count: leaves.length };
}
