export const TEAM_COPY = {
  // not in Pencil: the tab bar's accessible name and the row-menu label
  tabsLabel: "Bagian tim",
  rowActions: (name: string) => `Aksi untuk ${name}`,
  tabs: { active: "Aktif", archived: "Arsip", roles: "Peran" },
  cancel: "Batal",
  close: "Tutup",
  edit: "Ubah",
  delete: "Hapus",
  deleting: "Menghapus…",
  save: "Simpan",
  saving: "Menyimpan…",
  retry: "Coba lagi",
  serverErrorTitle: "Perubahan belum tersimpan",

  membersTitle: "Daftar anggota",
  membersCount: (status: "ACTIVE" | "ARCHIVED", count: number) =>
    status === "ACTIVE" ? `${String(count)} anggota aktif` : `${String(count)} anggota diarsipkan`,
  memberColumn: "ANGGOTA",
  whatsappColumn: "WHATSAPP",
  memberRolesColumn: "PERAN",
  searchPlaceholderDesktop: "Cari nama atau nomor WhatsApp",
  searchPlaceholderMobile: "Cari nama atau nomor",
  // not in Pencil: the search field's accessible name, its clear action and the live result count
  searchLabel: "Cari anggota",
  searchResultCount: (count: number) => `${String(count)} anggota cocok`,
  addMember: "Tambah anggota",
  addMemberShort: "Tambah",
  emptyActiveTitle: "Belum ada anggota tim",
  emptyActiveBody: "Catat freelancer yang sering kamu ajak, lalu pilih mereka di jadwal proyek.",
  emptyArchivedTitle: "Belum ada anggota yang diarsipkan",
  // not in Pencil: the archive empty body
  emptyArchivedBody: "Anggota yang diarsipkan muncul di sini.",
  noMatchTitle: "Tidak ada anggota yang cocok",
  noMatchBody: "Coba nama lain atau nomor WhatsApp-nya.",
  clearSearch: "Hapus pencarian",
  loadMore: "Muat lebih banyak",
  // not in Pencil: the load-more pending label
  loadingMore: "Memuat…",

  rolesTitle: "Daftar peran",
  rolesCountDesktop: (count: number) => `${String(count)} peran · dipilih saat menambah anggota`,
  rolesCountMobile: (count: number) => `${String(count)} peran`,
  roleColumn: "PERAN",
  usageColumn: "DIPAKAI",
  actionsColumn: "Aksi",
  usage: (count: number) => (count > 0 ? `${String(count)} anggota` : "Belum dipakai"),
  addRole: "Tambah peran",
  addRoleShort: "Tambah",
  // not in Pencil: edit title, the empty roles state and the toasts
  roleEditTitle: "Ubah peran",
  rolesEmptyTitle: "Belum ada peran",
  rolesEmptyBody: "Tambahkan peran agar bisa dipilih saat menambah anggota.",
  roleAddedTitle: "Peran ditambahkan",
  roleSavedTitle: "Perubahan disimpan",
  roleDeletedTitle: "Peran dihapus",
  roleDialogDescription: "Peran dipilih saat menambah anggota.",
  roleName: "Nama peran",
  roleErrors: {
    EMPTY: "Isi nama peran.",
    TOO_LONG: "Nama peran paling banyak 50 karakter.",
    DUPLICATE: "Peran ini sudah ada.",
  },
  roleDeleteBlockedTitle: (name: string) => `Peran ${name} tidak bisa dihapus`,
  roleDeleteBlockedBody: (count: number) => `Peran ini masih dipakai ${String(count)} anggota.`,
  roleDeleteTitle: (name: string) => `Hapus peran "${name}"?`,
  roleDeleteBody: "Peran ini dihapus dari daftar.",
} as const;
