import { foreignKey, timestamp, unique, uuid } from "drizzle-orm/pg-core";

import type { TenantKeyColumns, TenantRefColumns } from "./tenant.types";

// Tenant-table conventions (BR-WS-002, ADR-003). F-02 adds the `workspace` table and the
// workspace_id → workspace(id) FK on every tenant parent.

/** UUID primary key generated by Postgres. */
export const idColumn = () => uuid("id").primaryKey().defaultRandom();

/** The owning workspace; required on every tenant table, children included. */
export const workspaceIdColumn = () => uuid("workspace_id").notNull();

/** `created_at` / `updated_at` as `timestamptz NOT NULL DEFAULT now()`. */
export const auditColumns = () => ({
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Unique `(workspace_id, id)` on a tenant parent, so children can reference both columns.
 * @param table - the parent's `workspaceId` and `id` columns
 * @returns the unique constraint for the table's extra config
 */
export function tenantKey(table: TenantKeyColumns) {
  return unique().on(table.workspaceId, table.id);
}

/**
 * Composite FK `(workspace_id, <parent>_id) → parent(workspace_id, id)`: a child can't point
 * at another workspace's row.
 * @param child - the child's `workspaceId` and referencing column
 * @param parent - the parent's `workspaceId` and `id` columns
 * @returns the foreign key for the child's extra config
 */
export function tenantRef(child: TenantRefColumns, parent: TenantKeyColumns) {
  return foreignKey({
    columns: [child.workspaceId, child.column],
    foreignColumns: [parent.workspaceId, parent.id],
  });
}
