export const SETTINGS_COPY = {
  title: "Pengaturan workspace",
  name: "Nama workspace",
  brandName: "Nama brand",
  email: "Email kontak",
  phone: "Nomor telepon",
  address: "Alamat",
  prefix: "Prefiks invoice",
  currency: "Mata uang",
  currencyHelper: "Saat ini Shutrly hanya mendukung mata uang IDR.",
  save: "Simpan perubahan",
  prefixHelper: "Format nomor invoice untuk workspace ini.",
  idr: "IDR",
  saved: "Perubahan tersimpan",
} as const;
