export const SETTINGS_COPY = {
  brandTitle: "Identitas brand",
  brandDescription: "Nama dan brand yang dilihat klien di galeri dan invoice.",
  contactTitle: "Kontak",
  contactDescription: "Ditampilkan di invoice agar klien bisa menghubungimu.",
  invoiceTitle: "Invoice",
  invoiceDescription: "Format nomor invoice untuk workspace ini.",
  name: "Nama workspace",
  brandName: "Nama brand",
  brandNameHelper: "Kosongkan untuk memakai nama workspace.",
  email: "Email kontak",
  phone: "Telepon",
  address: "Alamat",
  prefix: "Prefiks invoice",
  prefixHelper: "2–6 huruf atau angka. Hanya berlaku untuk invoice baru.",
  currency: "Mata uang",
  currencyValue: "IDR — Rupiah Indonesia",
  currencyHelper: "Saat ini hanya IDR yang didukung.",
  save: "Simpan perubahan",
  saving: "Menyimpan…", // not in Pencil
  saved: "Perubahan tersimpan",
  savedBody: "Nama di sidebar dan branding untuk klien sudah diperbarui.",
  serverErrorTitle: "Perubahan belum tersimpan",
  serverErrorBody: "Terjadi kendala di server. Isianmu tetap ada — coba simpan lagi.",
} as const;
