// The client's *Hasil akhir* page (klien-8-hasil-akhir exports, F-10 Slice 9).
export const DELIVERY_SCREEN_COPY = {
  title: "Hasil akhir",
  subtitle: "Foto hasil akhir Anda sudah siap diunduh.",
  download: "Unduh",
  downloadAll: (count: number) => `Unduh semua (${String(count)})`,
  pickSeveral: "Pilih beberapa",
  readyTitle: "Hasil akhir sudah tersedia",
  readyBody: "Unduh satu per satu, beberapa, atau semuanya sekaligus.",
  cardTitle: "Foto hasil akhir",
  // F-20: one tab per package item instead of Edited / Print.
  groupMeta: (count: number, name: string) => `${String(count)} file · ${name}`,
  groupTab: (name: string, count: number) => `${name} · ${String(count)}`,
  editedMeta: (count: number) => `${String(count)} foto Edited`,
  printMeta: (count: number) => `${String(count)} file Print`,
  kindLabel: "Jenis file",
  editedTab: (count: number) => `Edited · ${String(count)}`,
  printTab: (count: number) => `Print · ${String(count)}`,
  confirmTitle: (count: number) => `Unduh semua ${String(count)} foto?`,
  confirmDescription: "Peramban Anda mengunduh file satu per satu.",
  confirmBody: "Jika diminta, izinkan unduhan berganda. Jangan tutup halaman ini sampai selesai.",
  cancel: "Batal",
  confirm: "Unduh semua",
  progressTitle: "Mengunduh hasil akhir",
  running: "Berjalan",
  progress: (done: number, total: number) => `${String(done)} dari ${String(total)} foto selesai`,
  stop: "Batalkan",
  failedTitle: (count: number) => `${String(count)} foto gagal diunduh`,
  failedBody: (names: string) => `${names} tidak bisa diunduh. Foto lain sudah masuk.`,
  retry: "Coba lagi",
  failedBadge: "Gagal",
  failedMeta: "Gagal diunduh",
  selectedTitle: (count: number) => `${String(count)} foto dipilih`,
  downloadSelected: (count: number) => `Unduh ${String(count)} foto`,
  viewerMeta: (kind: string, position: number, total: number) =>
    `Hasil akhir · ${kind} · ${String(position)} dari ${String(total)}`,
  downloadPhoto: "Unduh foto",
  edited: "Edited",
  print: "Print",
  // not in Pencil: accessible names, the viewer's missing text and an empty kind
  tileDownload: (fileName: string) => `Unduh ${fileName}`,
  tileSelect: (fileName: string) => `Pilih ${fileName}`,
  downloadMenu: "Pilihan unduhan",
  viewerMissing: "Foto ini tidak tersedia.",
  emptyKind: "Belum ada file di sini.",
} as const;
