import {
  Add01Icon,
  Alert02Icon,
  ApertureIcon,
  ArrowRight05Icon,
  BellIcon,
  Calendar03Icon,
  CameraFreeIcons,
  CheckFreeIcons,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightFreeIcons,
  Delete02Icon,
  FolderKanbanFreeIcons,
  GoogleIcon,
  InformationCircleIcon,
  LayoutGridFreeIcons,
  Loading03Icon,
  LogOutFreeIcons,
  Menu01Icon,
  MessageSquareTextFreeIcons,
  PackageFreeIcons,
  PanelLeftFreeIcons,
  PanelLeftOpenFreeIcons,
  ReceiptFreeIcons,
  Search01Icon,
  SearchXFreeIcons,
  SentIcon,
  SettingsFreeIcons,
  Share2,
  UnfoldMoreIcon,
  UserRoundCogFreeIcons,
  UsersFreeIcons,
  ViewIcon,
  ViewOffIcon,
  XFreeIcons,
} from "@hugeicons/core-free-icons";
import type { IconSvgElement } from "@hugeicons/react";

import type { IconName } from "./icon.types";

export const ICON_NAMES: readonly IconName[] = [
  "search",
  "chevron-down",
  "calendar",
  "eye",
  "eye-off",
  "circle-alert",
  "plus",
  "send",
  "arrow-right",
  "trash-2",
  "info",
  "google",
  "camera",
  "chevrons-up-down",
  "layout-grid",
  "folder-kanban",
  "users",
  "receipt",
  "package",
  "user-round-cog",
  "message-square-text",
  "share-2",
  "settings",
  "menu",
  "check",
  "chevron-right",
  "search-x",
  "panel-left",
  "panel-left-open",
  "log-out",
  "x",
  "loading-03",
  "bell",
  "chevron-left",
  "aperture",
];

export const ICON_REGISTRY: Record<IconName, IconSvgElement> = {
  search: Search01Icon,
  "chevron-down": ChevronDownIcon,
  calendar: Calendar03Icon,
  eye: ViewIcon,
  "eye-off": ViewOffIcon,
  "circle-alert": Alert02Icon,
  plus: Add01Icon,
  send: SentIcon,
  "arrow-right": ArrowRight05Icon,
  "trash-2": Delete02Icon,
  info: InformationCircleIcon,
  google: GoogleIcon,
  camera: CameraFreeIcons,
  "chevrons-up-down": UnfoldMoreIcon,
  "layout-grid": LayoutGridFreeIcons,
  "folder-kanban": FolderKanbanFreeIcons,
  users: UsersFreeIcons,
  receipt: ReceiptFreeIcons,
  package: PackageFreeIcons,
  "user-round-cog": UserRoundCogFreeIcons,
  "message-square-text": MessageSquareTextFreeIcons,
  "share-2": Share2,
  settings: SettingsFreeIcons,
  menu: Menu01Icon,
  check: CheckFreeIcons,
  "chevron-right": ChevronRightFreeIcons,
  "search-x": SearchXFreeIcons,
  "panel-left": PanelLeftFreeIcons,
  "panel-left-open": PanelLeftOpenFreeIcons,
  "log-out": LogOutFreeIcons,
  x: XFreeIcons,
  "loading-03": Loading03Icon,
  bell: BellIcon,
  "chevron-left": ChevronLeftIcon,
  aperture: ApertureIcon,
};
