import {
  Add01Icon,
  Alert02Icon,
  ApertureIcon,
  Archive01Icon,
  ArchiveRestoreIcon,
  ArrowDown01Icon,
  ArrowHorizontalIcon,
  ArrowRight05Icon,
  ArrowUp01Icon,
  BellIcon,
  BookOpen01Icon,
  BracesIcon,
  Calendar03Icon,
  CalendarCheck01Icon,
  CameraFreeIcons,
  CancelCircleIcon,
  CheckFreeIcons,
  CheckmarkCircle02Icon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightFreeIcons,
  Clock01Icon,
  CloudIcon,
  Database01Icon,
  Delete02Icon,
  DropboxIcon,
  FilterHorizontalIcon,
  Folder01Icon,
  FolderKanbanFreeIcons,
  FolderOpenIcon,
  GoogleIcon,
  HardDriveIcon,
  HashtagIcon,
  HourglassIcon,
  Image01Icon,
  InformationCircleIcon,
  LayoutGridFreeIcons,
  LeftToRightListBulletIcon,
  Link01Icon,
  Loading03Icon,
  LockIcon,
  LogOutFreeIcons,
  Menu01Icon,
  MessageCircleIcon,
  MessageSquareTextFreeIcons,
  MoreHorizontalIcon,
  PackageCheckIcon,
  PackageFreeIcons,
  PanelLeftFreeIcons,
  PanelLeftOpenFreeIcons,
  PencilEdit02Icon,
  PowerIcon,
  PrinterIcon,
  ReceiptFreeIcons,
  RefreshIcon,
  RotateCcwIcon,
  Search01Icon,
  SearchXFreeIcons,
  SentIcon,
  SettingsFreeIcons,
  Share2,
  TextAlignLeftIcon,
  TextIcon,
  ToggleOffIcon,
  UnfoldMoreIcon,
  UserRoundCogFreeIcons,
  UsersFreeIcons,
  ViewIcon,
  ViewOffIcon,
  Wallet01Icon,
  XFreeIcons,
} from "@hugeicons/core-free-icons";
import type { IconSvgElement } from "@hugeicons/react";

import type { IconName } from "./icon.types";

export const ICON_NAMES: readonly IconName[] = [
  "search",
  "chevron-down",
  "calendar",
  "eye",
  "eye-off",
  "circle-alert",
  "plus",
  "send",
  "arrow-right",
  "trash-2",
  "info",
  "google",
  "camera",
  "calendar-check",
  "list-filter",
  "circle-x",
  "refresh-cw",
  "circle-check-big",
  "chevrons-up-down",
  "layout-grid",
  "folder-kanban",
  "hard-drive",
  "folder-open",
  "folder",
  "power",
  "dropbox",
  "cloud",
  "database",
  "link",
  "more-horizontal",
  "printer",
  "clock",
  "book-open",
  "hash",
  "move-horizontal",
  "arrow-up",
  "arrow-down",
  "archive",
  "archive-restore",
  "lock",
  "type",
  "align-left",
  "toggle-left",
  "list",
  "users",
  "receipt",
  "package",
  "user-round-cog",
  "message-square-text",
  "message-circle",
  "share-2",
  "settings",
  "menu",
  "check",
  "chevron-right",
  "search-x",
  "panel-left",
  "panel-left-open",
  "log-out",
  "x",
  "loading-03",
  "bell",
  "chevron-left",
  "aperture",
  "image",
  "hourglass",
  "package-check",
  "wallet",
  "rotate-ccw",
  "braces",
  "pencil",
];

export const ICON_REGISTRY: Record<IconName, IconSvgElement> = {
  search: Search01Icon,
  "chevron-down": ChevronDownIcon,
  calendar: Calendar03Icon,
  eye: ViewIcon,
  "eye-off": ViewOffIcon,
  "circle-alert": Alert02Icon,
  plus: Add01Icon,
  send: SentIcon,
  "arrow-right": ArrowRight05Icon,
  "trash-2": Delete02Icon,
  info: InformationCircleIcon,
  google: GoogleIcon,
  camera: CameraFreeIcons,
  "calendar-check": CalendarCheck01Icon,
  "list-filter": FilterHorizontalIcon,
  "circle-x": CancelCircleIcon,
  "refresh-cw": RefreshIcon,
  "circle-check-big": CheckmarkCircle02Icon,
  "chevrons-up-down": UnfoldMoreIcon,
  "layout-grid": LayoutGridFreeIcons,
  "folder-kanban": FolderKanbanFreeIcons,
  "hard-drive": HardDriveIcon,
  "folder-open": FolderOpenIcon,
  folder: Folder01Icon,
  power: PowerIcon,
  dropbox: DropboxIcon,
  cloud: CloudIcon,
  database: Database01Icon,
  link: Link01Icon,
  "more-horizontal": MoreHorizontalIcon,
  printer: PrinterIcon,
  clock: Clock01Icon,
  "book-open": BookOpen01Icon,
  hash: HashtagIcon,
  "move-horizontal": ArrowHorizontalIcon,
  "arrow-up": ArrowUp01Icon,
  "arrow-down": ArrowDown01Icon,
  archive: Archive01Icon,
  "archive-restore": ArchiveRestoreIcon,
  lock: LockIcon,
  type: TextIcon,
  "align-left": TextAlignLeftIcon,
  "toggle-left": ToggleOffIcon,
  list: LeftToRightListBulletIcon,
  users: UsersFreeIcons,
  receipt: ReceiptFreeIcons,
  package: PackageFreeIcons,
  "user-round-cog": UserRoundCogFreeIcons,
  "message-square-text": MessageSquareTextFreeIcons,
  "message-circle": MessageCircleIcon,
  "share-2": Share2,
  settings: SettingsFreeIcons,
  menu: Menu01Icon,
  check: CheckFreeIcons,
  "chevron-right": ChevronRightFreeIcons,
  "search-x": SearchXFreeIcons,
  "panel-left": PanelLeftFreeIcons,
  "panel-left-open": PanelLeftOpenFreeIcons,
  "log-out": LogOutFreeIcons,
  x: XFreeIcons,
  "loading-03": Loading03Icon,
  bell: BellIcon,
  "chevron-left": ChevronLeftIcon,
  aperture: ApertureIcon,
  image: Image01Icon,
  hourglass: HourglassIcon,
  "package-check": PackageCheckIcon,
  wallet: Wallet01Icon,
  "rotate-ccw": RotateCcwIcon,
  braces: BracesIcon,
  pencil: PencilEdit02Icon,
};
