export const CATALOG_COPY = {
  tabsLabel: "Bagian layanan",
  addService: "Tambah layanan",
  editServiceTitle: "Ubah layanan",
  editServiceDescription: "Perbarui nama, kategori, atau harga dasar layanan.",
  addCategory: "Tambah kategori",
  addCategoryInline: "+ Kategori baru",
  addItem: "Tambah item",
  addField: "Tambah field",
  editItemValue: "Ubah nilai",
  editField: "Ubah field",
  removeItem: "Hapus dari layanan",
  removeField: "Hapus field",
  removeItemTitle: (name: string) => `Hapus ${name} dari layanan?`,
  removeFieldTitle: (name: string) => `Hapus field “${name}”?`,
  removeDescription: "Tindakan ini tidak bisa dibatalkan.",
  add: "Tambah",
  edit: "Ubah",
  rename: "Ganti nama",
  archive: "Arsipkan",
  unarchive: "Aktifkan",
  delete: "Hapus",
  archived: "Diarsipkan",
  archivedBannerTitle: "Layanan ini diarsipkan",
  archivedBannerBody:
    "Tidak bisa dipilih untuk proyek baru. Proyek yang sudah dibuat tidak berubah.",
  active: "Aktif",
  rowActions: (name: string) => `Aksi untuk ${name}`,
  moveUp: "Naikkan",
  moveDown: "Turunkan",
  servicesEmptyTitle: "Belum ada layanan",
  servicesEmptyBody:
    "Buat kategori dulu, misalnya Wisuda atau Wedding, lalu tambahkan layanan dengan harga dan isi paketnya.",
  categoriesTitle: "Kategori",
  categoriesDescription: "Mengelompokkan layanan di tab Layanan.",
  categoryMeta: (count: number) => `${String(count)} layanan`,
  categoryUsage: (count: number) => `${String(count)} layanan`,
  serviceUsage: (count: number) => `${String(count)} item paket`,
  selectionGroupTitle: "Dipilih klien",
  selectionGroupDescription: "Jadi jatah pilihan foto klien di gallery. Selalu angka bulat.",
  otherGroupTitle: "Item lainnya",
  otherGroupDescription: "Keterangan paket yang tidak dipilih klien.",
  valueTypes: { NUMBER: "Angka", RANGE: "Rentang" },
  selectionTypes: { EDIT: "Foto edit", PRINT: "Foto cetak" },
  selectionTypeDescriptions: {
    EDIT: "Klien memilih foto untuk diedit. Dihitung per foto.",
    PRINT: "Klien memilih foto dan jumlah cetaknya.",
  },
  definitionMeta: (valueType: string, unit: string | null, usage: number) =>
    [valueType, unit, usage > 0 ? `dipakai di ${String(usage)} layanan` : "belum dipakai"]
      .filter(Boolean)
      .join(" · "),
  definitionUsage: (count: number) => `${String(count)} layanan memakai item ini`,
  nameItem: "Nama item",
  valueTypeDescriptions: {
    NUMBER: "Satu nilai, mis. 25 foto atau 2 jam.",
    RANGE: "Nilai minimum–maksimum, mis. 1–2 orang.",
  },
  unitHelp: "Ditulis setelah nilai, mis. 2 buah.",
  selectionSwitch: "Dipakai untuk pilihan foto klien",
  selectionType: "Jenis pilihan",
  definitionDialogAddTitle: "Tambah item paket",
  definitionDialogEditTitle: "Ubah item paket",
  definitionDialogDescription: "Dipakai ulang di semua layanan workspace ini.",
  valueType: "Tipe nilai",
  unit: "Satuan",
  category: "Kategori",
  categoryPlaceholder: "Pilih kategori",
  nameCategory: "Nama kategori",
  categoryDialogAddTitle: "Tambah kategori",
  categoryDialogRenameTitle: "Ganti nama kategori",
  categoryDialogDescription: "Mis. Wisuda, Wedding, Keluarga.",
  nameCategoryPlaceholder: "Contoh: Prewedding",
  nameService: "Nama layanan",
  addServiceTitle: "Tambah layanan",
  addServiceDescription: "Isi paket dan field booking diatur setelah layanan dibuat.",
  nameServicePlaceholder: "Contoh: Wisuda Basic",
  basePrice: "Harga dasar",
  basePriceHelp: "Dalam rupiah, tanpa desimal.",
  save: "Simpan",
  cancel: "Batal",
  pick: "Pilih",
  undo: "Batalkan",
  archivedToast: (kind: string) => `${kind} diarsipkan`,
  unarchivedToast: "Diaktifkan lagi",
  savedToast: "Perubahan tersimpan",
  serverErrorTitle: "Perubahan belum tersimpan",
  serverErrorBody: "Periksa koneksi lalu coba lagi.",
  retry: "Coba lagi",
  deletedToast: "Dihapus",
  status: "Status",
  itemsTitle: "Item paket",
  itemsDescription: "Disalin ke proyek dalam urutan ini.",
  itemsEmpty:
    "Belum ada item paket. Tambahkan isi paket, misalnya Foto edit 25 atau Jumlah orang 1–2.",
  fieldsTitle: "Field booking",
  fieldsDescription: "Diisi saat membuat proyek dari layanan ini.",
  fieldsEmpty:
    "Belum ada field booking. Tambahkan kalau proyek butuh info tambahan, misalnya Nama kampus.",
  infoTitle: "Info layanan",
  infoDescription: "Nama, kategori dan harga dasar.",
  fieldTypes: {
    TEXT: "Teks",
    TEXTAREA: "Teks panjang",
    NUMBER: "Angka",
    DATE: "Tanggal",
    BOOLEAN: "Ya/Tidak",
    SELECT: "Pilihan",
  },
  fieldMeta: (type: string, isRequired: boolean, options: readonly string[] | null) => {
    const requirement = isRequired ? "Wajib" : "Opsional";
    return options ? `${type}: ${options.join(", ")} · ${requirement}` : `${type} · ${requirement}`;
  },
  addItemTitle: "Tambah item paket",
  addItemDescription: "Tambahkan isi paket ke layanan ini.",
  itemPicker: "Item paket",
  value: "Nilai",
  minimum: "Minimum",
  maximum: "Maksimum",
  fieldName: "Nama field",
  fieldType: "Tipe",
  options: "Pilihan",
  addOption: "Pisahkan pilihan dengan koma.",
  addOptionButton: "Tambah pilihan",
  option: "Pilihan",
  optionLabel: (index: number) => `Pilihan ${String(index)}`,
  removeOption: (name: string) => `Hapus pilihan ${name || "baru"}`,
  optionError: (code: string) => {
    if (code === "OPTION_DUPLICATE") return "Pilihan ini sudah ada.";
    if (code === "OPTION_EMPTY") return "Isi pilihan.";
    if (code === "OPTION_TOO_LONG") return "Maksimal 60 karakter.";
    return undefined;
  },
  requiredSwitch: "Wajib diisi",
  addFieldTitle: "Tambah field booking",
  fieldDialogDescription: "Diisi saat membuat proyek dari layanan ini.",
  deleteTitle: (name: string) => `Hapus kategori “${name}”?`,
  deleteAllowedBody: "Belum dipakai di mana pun. Tindakan ini tidak bisa dibatalkan.",
  deleteBlockedTitle: "Tidak bisa dihapus",
  deleteBlockedBody: (name: string) =>
    `“${name}” masih dipakai layanan. Arsipkan supaya tidak bisa dipilih untuk yang baru.`,
  deleteConfirm: "Hapus",
  itemValueSeparator: ": ",
  errors: {
    EMPTY: "Isi nama.",
    TOO_LONG: "Maksimal 60 karakter.",
    NAME_TAKEN: "Nama ini sudah dipakai.",
    UNIT_TOO_LONG: "Satuan maksimal 20 karakter.",
    SELECTION_NEEDS_NUMBER: "Pilihan klien hanya untuk tipe Angka.",
    SELECTION_TYPE_REQUIRED: "Pilih jenis pilihan.",
    SELECTION_TYPE_UNEXPECTED: "Jenis pilihan hanya untuk item yang dipilih klien.",
    LOCKED: "Tipe nilai tidak bisa diubah karena sudah dipakai layanan.",
    CATEGORY_REQUIRED: "Pilih kategori.",
    INACTIVE_REFERENCE: "Pilihan ini sudah diarsipkan.",
    INVALID: "Isi angka yang valid.",
    NEGATIVE: "Tidak boleh negatif.",
    TOO_MANY_DECIMALS: "Maksimal 2 angka di belakang koma.",
    TOO_LARGE: "Angkanya terlalu besar.",
    NOT_WHOLE: "Harus angka bulat.",
    MIN_GREATER_THAN_MAX: "Maksimum harus sama atau lebih dari minimum.",
    DUPLICATE_DEFINITION: "Item ini sudah ada di layanan.",
    NOT_FOUND: "Item tidak ditemukan.",
    OPTIONS_REQUIRED: "Tambahkan minimal satu pilihan.",
    OPTION_EMPTY: "Isi pilihan.",
    OPTION_TOO_LONG: "Maksimal 60 karakter.",
    OPTION_DUPLICATE: "Pilihan ini sudah ada.",
    TOO_MANY_OPTIONS: "Maksimal 50 pilihan.",
    SAVE_FAILED: "Perubahan belum tersimpan.",
  },
  lockedDefinitionDescription: "Tipe dan pilihan terkunci karena item ini sudah dipakai layanan.",
} as const;
