export const PROVIDER_COPY = {
  GOOGLE_DRIVE: {
    title: "Google Drive",
    description: "Folder yang dibagikan lewat link, hanya dibaca.",
    icon: "hard-drive",
  },
  DROPBOX: { title: "Dropbox", icon: "dropbox" },
  ONEDRIVE: { title: "OneDrive", icon: "cloud" },
  AMAZON_S3: { title: "Amazon S3", icon: "database" },
  CUSTOM_URL: { title: "Custom URL", icon: "link" },
} as const;

export const SOURCE_COPY = {
  listTitle: "Daftar sumber",
  listDescription: "Pilih salah satu saat membuat gallery. Sumber nonaktif tidak bisa dipilih.",
  listDescriptionMobile: "Pilih salah satu saat membuat gallery.",
  loading: "Memuat sumber foto",
  add: "Tambah sumber",
  addShort: "Tambah",
  active: "Aktif",
  inactive: "Nonaktif",
  comingSoon: "Segera hadir",
  rowActions: (name: string) => `Aksi untuk ${name}`,
  rename: "Ganti nama",
  deactivate: "Nonaktifkan",
  activate: "Aktifkan",
  delete: "Hapus",
  emptyTitle: "Belum ada sumber foto",
  emptyBody: "Tambahkan Google Drive agar foto bisa ditautkan ke gallery.",
  guideTitle: "Menyiapkan folder Google Drive",
  guideDescription:
    "Shutrly hanya membaca foto di folder yang kamu bagikan. Tautannya ditempel saat membuat gallery.",
  guideDescriptionMobile: "Tautan folder ditempel saat membuat gallery.",
  steps: [
    "Buat satu folder utama untuk setiap proyek.",
    "Taruh foto proof langsung di folder utama, tidak di dalam subfolder.",
    "Untuk hasil akhir, nanti tambahkan subfolder edited dan print.",
    "Bagikan folder utama: Akses umum → Siapa saja yang memiliki link, peran Pelihat.",
  ],
  treeRoot: "Wedding Rina & Dimas",
  treeRootMeta: "foto proof langsung di sini",
  treeEdited: "hasil edit, ditambahkan nanti",
  treePrint: "file cetak, ditambahkan nanti",
  warningTitle: "Tautan Drive bisa melewati password gallery",
  warningBody:
    "Siapa pun yang memegang tautan folder Drive bisa membuka fotonya langsung, tanpa link gallery dan password. Ke klien, bagikan hanya link gallery dari Shutrly.",
  warningBodyShort:
    "Siapa pun yang memegang tautan folder Drive bisa membuka fotonya langsung. Ke klien, bagikan hanya link gallery dari Shutrly.",
  addTitle: "Tambah sumber foto",
  addDescription: "Pilih tempat foto disimpan. Saat ini Shutrly mendukung Google Drive.",
  providerLabel: "Provider",
  nameLabel: "Nama sumber",
  namePlaceholder: "mis. Google Drive Arsip",
  nameHelper: "Muncul saat memilih sumber untuk gallery.",
  cancel: "Batal",
  adding: "Menambahkan…",
  renameTitle: "Ganti nama sumber",
  renameDescription: "Nama baru langsung dipakai di semua tempat.",
  save: "Simpan",
  saving: "Menyimpan…",
  deleteTitle: (name: string) => `Hapus sumber "${name}"?`,
  deleteBody:
    "Sumber ini hilang dari workspace. Folder dan foto di Google Drive tidak terpengaruh.",
  deleteMeta: "Folder dan foto di Google Drive tidak terpengaruh.",
  deleteConfirm: "Hapus sumber",
  inUse: "Sumber ini dipakai gallery. Nonaktifkan saja.",
  addedTitle: "Sumber ditambahkan",
  addedBody: (name: string) => `${name} siap dipilih saat membuat gallery.`,
  renamedTitle: "Nama sumber diperbarui",
  renamedBody: (name: string) => `${name} sudah diperbarui.`,
  deactivatedTitle: "Sumber dinonaktifkan",
  deactivatedBody: (name: string) => `${name} tidak bisa dipilih untuk gallery baru.`,
  undo: "Batalkan",
  activatedTitle: "Sumber diaktifkan",
  activatedBody: (name: string) => `${name} sudah diaktifkan.`,
  deletedTitle: "Sumber dihapus",
  deletedBody: (name: string) => `${name} sudah dihapus.`,
  serverErrorTitle: "Perubahan belum tersimpan",
  serverErrorBody: "Terjadi kendala di server. Data sumbermu tidak berubah.",
  retry: "Coba lagi",
  nameErrors: {
    EMPTY: "Isi nama sumber.",
    TOO_LONG: "Nama sumber maksimal 60 karakter.",
    NAME_TAKEN: "Nama ini sudah dipakai di workspace ini.",
    PROVIDER_UNAVAILABLE: "Provider ini belum tersedia.",
  },
} as const;
