const TAB_NAME = {
  ACTIVE: "Aktif",
  COMPLETED: "Selesai",
  CANCELLED: "Dibatalkan",
} as const;

const COUNT_NOUN = {
  ACTIVE: "aktif",
  COMPLETED: "selesai",
  CANCELLED: "dibatalkan",
} as const;

export const PROJECT_COPY = {
  parentLabel: "Proyek",
  createTitle: "Proyek baru",
  createSubtitle: "Pilih klien dan layanan, lalu catat apa yang kalian sepakati.",
  clientServiceTitle: "Klien & layanan",
  clientLabel: "Klien",
  clientPlaceholder: "Cari atau tambah klien",
  clientGroupLabel: (count: number) => `KLIEN · ${String(count)} COCOK`,
  clientNoMatchLabel: (query: string) => `TIDAK ADA KLIEN “${query}”`,
  clientCreateLabel: (query: string) => `Tambah klien baru “${query}”`,
  clientNoNumber: "Belum ada nomor WhatsApp",
  clientNote: (number: string, projectCount: number) =>
    `${number} · ${String(projectCount)} proyek`,
  serviceLabel: "Layanan",
  servicePlaceholder: "Pilih layanan",
  serviceHelper: (category: string, price: string) => `${category} · harga dasar ${price}`,
  packageTitle: "Isi paket",
  packageDescriptionDesktop: (service: string) =>
    `Disalin dari ${service}. Perubahan hanya berlaku untuk proyek ini.`,
  packageDescriptionMobile: (service: string) => `Dari ${service}. Hanya untuk proyek ini.`,
  packageEmptyTitle: "Layanan ini belum punya item paket",
  packageEmptyBody:
    "Tambahkan item bila perlu. Item yang kamu tambah hanya berlaku untuk proyek ini.",
  selectionEdit: "pilihan edit",
  // not in Pencil
  selectionPrint: "pilihan cetak",
  detailTitle: "Detail proyek",
  titleLabel: "Judul proyek",
  titlePlaceholderDesktop: "Terisi otomatis setelah memilih layanan",
  titlePlaceholderMobile: "Terisi setelah memilih layanan",
  titleExample: (service: string, client: string) => `Contoh: ${service} — ${client}`,
  titleHelper: "Terisi otomatis dari layanan dan klien. Bisa diubah.",
  priceLabel: "Harga sepakat",
  pricePrefix: "Rp",
  pricePlaceholder: "0",
  priceHelper: (price: string) => `Harga dasar layanan: ${price}`,
  notesLabel: "Catatan internal",
  notesPlaceholder: "Hanya kamu yang bisa melihat catatan ini.",
  scheduleTitle: "Jadwal",
  scheduleDescriptionDesktop: "Sesi pemotretan. Minimal satu sesi untuk Buat proyek.",
  scheduleDescriptionMobile: "Minimal satu sesi untuk Buat proyek.",
  addSessionDesktop: "Tambah sesi",
  addSessionMobile: "Tambah",
  scheduleEmptyTitle: "Belum ada sesi",
  scheduleEmptyBody: "Catat tanggal, jam, dan lokasi pemotretan. Draf boleh disimpan tanpa sesi.",
  sessionActions: (name: string) => `Aksi untuk sesi ${name}`,
  editSession: "Ubah",
  deleteSession: "Hapus",
  fieldsTitle: "Field booking",
  fieldsDescription: (service: string) =>
    `Dari layanan ${service}. Semua field tanpa (opsional) wajib diisi, juga untuk draf.`,
  fieldSelectPlaceholder: (field: string) => `Pilih ${field.toLowerCase()}`,
  // not in Pencil
  fieldYes: "Ya",
  // not in Pencil
  fieldNo: "Tidak",
  saveDraft: "Simpan draf",
  // not in Pencil
  savingDraft: "Menyimpan draf…",
  create: "Buat proyek",
  creating: "Membuat proyek…",
  sessionDialogTitle: "Tambah sesi",
  sessionEditTitle: "Ubah sesi",
  sessionDialogDescription: "Sesi disimpan bersama proyek.",
  sessionName: "Nama sesi",
  sessionNamePlaceholder: "Contoh: Akad, Resepsi, Foto keluarga",
  sessionDate: "Tanggal",
  sessionDatePlaceholder: "Pilih tanggal",
  sessionStart: "Jam mulai",
  sessionEnd: "Jam selesai",
  sessionLocation: "Lokasi",
  sessionLocationPlaceholder: "Alamat atau nama tempat",
  sessionCancel: "Batal",
  sessionSave: "Tambah sesi",
  sessionSaveEdit: "Simpan",
  serverErrorTitle: "Perubahan belum tersimpan",
  serverErrorBody: "Terjadi kendala di server. Isian formulirmu masih ada.",
  retry: "Coba lagi",
  toastCreatedTitle: "Proyek dibuat",
  toastCreatedBody: (title: string) => `${title} sudah Dibooking.`,
  toastDraftSavedTitle: "Draf disimpan",
  // not in Pencil
  toastDraftSavedBody: (title: string) => `${title} tersimpan sebagai draf.`,
  infoTitle: "Info",
  infoClient: "Klien",
  infoService: "Layanan",
  infoPrice: "Harga sepakat",
  infoNotes: "Catatan internal",
  emptyValue: "—",
  packageDescriptionDetailDesktop: (service: string) =>
    `Disalin dari ${service}. Bisa diubah sampai pemotretan dimulai.`,
  packageDescriptionDetailMobile: "Bisa diubah sampai pemotretan dimulai.",
  scheduleDescriptionDetailDesktop: "Sesi pemotretan, urut tanggal.",
  scheduleDescriptionDetailMobile: "Urut tanggal.",
  scheduleDetailEmptyBody: "Tambahkan minimal satu sesi sebelum konfirmasi booking.",
  fieldsDescriptionDetailDesktop: (service: string) =>
    `Disalin dari ${service} saat proyek dibuat.`,
  fieldsDescriptionDetailMobile: (service: string) => `Disalin dari ${service}.`,
  lockedDescription: "Terkunci sejak pemotretan dimulai.",
  cancelledDescription: "Proyek dibatalkan, tidak bisa diubah.",
  cancelledTitle: "Proyek dibatalkan",
  cancelledBy: (name: string, date: string) => `Dibatalkan oleh ${name} pada ${date}.`,
  // not in Pencil
  cancelledAnonymous: (date: string) => `Dibatalkan pada ${date}.`,
  cancelledReason: (reason: string) => `Alasan: ${reason}.`,
  metaNoSchedule: "Belum ada jadwal",
  metaNext: "Sesi berikutnya",
  metaLast: "Sesi terakhir",
  metaExtra: (count: number) => `+${String(count)} sesi`,
  stepConfirm: "Konfirmasi booking",
  stepConfirmPending: "Konfirmasi booking…",
  stepStart: "Mulai pemotretan",
  stepStartPending: "Mulai pemotretan…",
  stepFinish: "Selesai pemotretan",
  stepFinishPending: "Selesai pemotretan…",
  toastConfirmedTitle: "Booking dikonfirmasi",
  toastStartedTitle: "Pemotretan dimulai",
  toastStartedBody: "Isi paket dan harga sekarang terkunci.",
  toastFinishedTitle: "Pemotretan selesai",
  toastStaleTitle: "Status proyek sudah berubah",
  // not in Pencil
  toastStaleBody: "Halaman dimuat ulang dengan data terbaru.",
  toastSessionRequiredTitle: "Tambahkan minimal satu sesi sebelum konfirmasi booking.",
  statusDraft: "Draf",
  statusBooked: "Dibooking",
  statusShooting: "Pemotretan",
  statusPostProcessing: "Pascaproduksi",
  statusDelivered: "Terkirim",
  statusCompleted: "Selesai",
  statusCancelled: "Dibatalkan",
  listTitle: "Daftar proyek",
  listCount: (tab: "ACTIVE" | "COMPLETED" | "CANCELLED", count: number) =>
    `${String(count)} proyek ${COUNT_NOUN[tab]}`,
  clientService: (client: string, service: string) => `${client} · ${service}`,
  tabsLabel: "Status proyek",
  tabActive: "Aktif",
  tabCompleted: "Selesai",
  tabCancelled: "Dibatalkan",
  listAddDesktop: "Proyek baru",
  listAddMobile: "Baru",
  searchLabel: "Cari judul atau nama klien",
  clearSearch: "Hapus pencarian",
  searchResultCount: (count: number) => `${String(count)} proyek ditemukan`,
  columnProject: "PROYEK",
  columnEvent: "ACARA",
  columnStatus: "STATUS",
  columnActions: "Aksi",
  emptyActiveTitle: "Belum ada proyek",
  emptyActiveBody: "Buat proyek untuk mencatat klien, layanan, dan harga yang kamu sepakati.",
  emptyCompletedTitle: "Belum ada proyek yang selesai",
  emptyCompletedBody: "Proyek pindah ke sini setelah hasil akhirnya dikirim dan diselesaikan.",
  emptyCancelledTitle: "Belum ada proyek yang dibatalkan",
  emptyCancelledBody: "Proyek yang kamu batalkan muncul di sini, lengkap dengan alasannya.",
  noMatchTitle: "Tidak ada proyek yang cocok",
  noMatchBody: "Coba judul lain, atau ketik sebagian nama klien.",
  loadMore: "Muat lebih banyak",
  loadingMore: "Memuat…",
  listSubtitleDesktop: "Setiap pemotretan yang kamu pegang, dari draf sampai selesai.",
  listSubtitleMobile: "Pemotretan dari draf sampai selesai.",
  filterButton: "Filter",
  filterBadgeLabel: "aktif",
  filterTitle: "Filter proyek",
  filterDescription: (tab: "ACTIVE" | "COMPLETED" | "CANCELLED") =>
    `Berlaku untuk tab ${TAB_NAME[tab]}.`,
  filterStatus: "Status",
  filterStatusPlaceholder: "Semua status",
  filterSchedule: "Jadwal",
  filterFrom: "Dari",
  filterTo: "Sampai",
  filterDatePlaceholder: "Pilih tanggal",
  filterNoSchedule: "Sertakan proyek tanpa jadwal",
  filterService: "Layanan",
  filterServicePlaceholder: "Semua layanan",
  filterClient: "Klien",
  filterClientPlaceholder: "Semua klien",
  filterClientGroup: (count: number) => `KLIEN · ${String(count)} COCOK`,
  filterArchivedClient: (name: string) => `${name} (diarsipkan)`,
  filterToBeforeFrom: "Tanggal Sampai harus sama atau setelah Dari.",
  filterReset: "Reset",
  filterApply: "Terapkan",
} as const;
