const TAB_NAME = {
  ACTIVE: "Aktif",
  COMPLETED: "Selesai",
  CANCELLED: "Dibatalkan",
} as const;

const COUNT_NOUN = {
  ACTIVE: "aktif",
  COMPLETED: "selesai",
  CANCELLED: "dibatalkan",
} as const;

export const PROJECT_COPY = {
  parentLabel: "Proyek",
  createTitle: "Proyek baru",
  createSubtitle: "Pilih klien dan layanan, lalu catat apa yang kalian sepakati.",
  clientServiceTitle: "Klien & layanan",
  clientLabel: "Klien",
  clientPlaceholder: "Cari atau tambah klien",
  clientGroupLabel: (count: number) => `KLIEN · ${String(count)} COCOK`,
  clientNoMatchLabel: (query: string) => `TIDAK ADA KLIEN “${query}”`,
  noServiceTitle: "Belum ada layanan aktif",
  noServiceBody:
    "Proyek dibuat dari layanan. Buat atau aktifkan layanan dulu, lalu kembali ke sini.",
  noServiceAction: "Buka Layanan",
  changeServiceTitle: "Ganti layanan?",
  changeServiceBody: (service: string) =>
    `Perubahan isi paket akan hilang. Isi paket diganti dengan isi ${service}.`,
  changeServiceConfirm: "Ganti layanan",
  clientDialogDescription: "Klien baru langsung dipilih untuk proyek ini.",
  clientCreateLabel: (query: string) => `Tambah klien baru “${query}”`,
  clientNoNumber: "Belum ada nomor WhatsApp",
  clientNote: (number: string, projectCount: number) =>
    `${number} · ${String(projectCount)} proyek`,
  serviceLabel: "Layanan",
  servicePlaceholder: "Pilih layanan",
  serviceHelper: (category: string, price: string) => `${category} · harga dasar ${price}`,
  packageTitle: "Isi paket",
  packageDescriptionDesktop: (service: string) =>
    `Disalin dari ${service}. Perubahan hanya berlaku untuk proyek ini.`,
  packageDescriptionMobile: (service: string) => `Dari ${service}. Hanya untuk proyek ini.`,
  packageEmptyTitle: "Layanan ini belum punya item paket",
  packageEmptyBody:
    "Tambahkan item bila perlu. Item yang kamu tambah hanya berlaku untuk proyek ini.",
  // not in Pencil
  pickModes: { COUNT: "hitung foto", QUANTITY: "jumlah per foto" },
  // not in Pencil: F-10 D-10c refusals
  selectionInUseTitle: "Klien sudah memilih foto untuk item ini",
  selectionInUseBody: (usage: number, unit: string | null) =>
    `Sudah dipilih ${[String(usage), unit].filter(Boolean).join(" ")}. Nilai tidak bisa di bawah itu, dan item tidak bisa dihapus.`,
  // not in Pencil
  selectionClosedTitle: "Pilihan klien untuk item ini sudah dikirim",
  selectionClosedBody: "Ubah item ini setelah membuka lagi pilihannya.",
  // not in Pencil
  selectionHasAddOnTitle: "Item ini dipakai add-on yang sudah disetujui",
  selectionHasAddOnBody: "Batalkan add-on itu dulu, lalu hapus item ini.",
  detailTitle: "Detail proyek",
  titleLabel: "Judul proyek",
  titlePlaceholderDesktop: "Terisi otomatis setelah memilih layanan",
  titlePlaceholderMobile: "Terisi setelah memilih layanan",
  titleExample: (service: string, client: string) => `Contoh: ${service} — ${client}`,
  titleHelper: "Terisi otomatis dari layanan dan klien. Bisa diubah.",
  priceLabel: "Harga sepakat",
  pricePrefix: "Rp",
  pricePlaceholder: "0",
  priceHelper: (price: string) => `Harga dasar layanan: ${price}`,
  notesLabel: "Catatan internal",
  notesPlaceholder: "Hanya kamu yang bisa melihat catatan ini.",
  scheduleTitle: "Jadwal",
  scheduleDescriptionDesktop: "Sesi pemotretan. Minimal satu sesi untuk Buat proyek.",
  scheduleDescriptionMobile: "Minimal satu sesi untuk Buat proyek.",
  addSessionDesktop: "Tambah sesi",
  addSessionMobile: "Tambah",
  scheduleEmptyTitle: "Belum ada sesi",
  scheduleEmptyBody: "Catat tanggal, jam, dan lokasi pemotretan. Draf boleh disimpan tanpa sesi.",
  sessionActions: (name: string) => `Aksi untuk sesi ${name}`,
  editSession: "Ubah",
  editSessionDetail: "Ubah sesi",
  addTeam: "Tambah tim",
  manageTeam: "Atur tim",
  // not in Pencil: the accessible names of the team controls
  addTeamFor: (session: string) => `Tambah tim untuk ${session}`,
  teamGroupLabel: (session: string, count: number) => `Tim ${session}: ${String(count)} anggota`,
  avatarTooltip: (name: string, role: string) => `${name} · ${role}`,
  assignTitle: (session: string) => `Tambah anggota · ${session}`,
  assignMember: "Anggota",
  assignMemberHint: "Hanya anggota aktif yang belum ada di sesi ini.",
  // not in Pencil: the empty member field's placeholder
  assignMemberPlaceholder: "Pilih anggota",
  assignRole: "Peran",
  assignRolePlaceholder: "Pilih peran",
  assignRoleHint: (name: string) => `Peran yang dimiliki ${name}.`,
  assignSubmit: "Tambah",
  assignSubmitting: "Menambahkan…",
  assignCancel: "Batal",
  assignEmptyTitle: "Belum ada anggota tim aktif",
  assignEmptyBody: "Tambahkan anggota di halaman Tim dulu, lalu kembali ke sini.",
  assignEmptyAction: "Buka Tim",
  assignedToastTitle: "Anggota ditambahkan",
  assignedToastBody: (name: string, session: string, role: string) =>
    `${name} bertugas di ${session} sebagai ${role}.`,
  // not in Pencil: the assignment errors and the cancelled toast
  assignErrors: {
    ALREADY_ASSIGNED: (name: string) => `${name} sudah ada di sesi ini.`,
    MEMBER_ARCHIVED: (name: string) => `${name} sudah diarsipkan.`,
    ROLE_NOT_HELD: (name: string) => `${name} tidak punya peran ini lagi.`,
  },
  teamCancelledToast: "Proyek dibatalkan; tim tidak bisa diubah.",
  // not in Pencil: the team field of the session dialog (AC-TEAM-028)
  sessionTeamLabel: "Tim",
  sessionTeamHint: "Pilih anggota dan perannya di sesi ini. Bisa diubah nanti lewat Atur tim.",
  sessionTeamNone: "Belum ada anggota tim aktif. Tambahkan di halaman Tim dulu.",
  sessionTeamMember: "Anggota tim",
  sessionTeamRole: "Peran di sesi ini",
  sessionTeamListLabel: "Tim sesi ini",
  teamTitle: (session: string) => `Tim · ${session}`,
  teamAddMember: "Tambah anggota",
  teamDone: "Selesai",
  teamClose: "Tutup",
  teamCancelledNote: "Proyek dibatalkan, tim tidak bisa diubah.",
  // not in Pencil: the list's accessible name and the archived marker after a name
  teamListLabel: (session: string) => `Tim ${session}`,
  teamArchivedMark: "(diarsipkan)",
  teamRemoveLabel: "Hapus dari sesi",
  removeAssignmentTitle: (name: string, session: string) => `Hapus ${name} dari ${session}?`,
  removeAssignmentBody: (firstName: string) =>
    `Penugasannya dihapus dari sesi ini. ${firstName} tetap ada di Tim.`,
  removeAssignmentConfirm: "Hapus dari sesi",
  // not in Pencil: the removal toast
  removedToastTitle: "Anggota dihapus dari sesi",
  removedToastBody: (name: string, session: string) => `${name} tidak lagi bertugas di ${session}.`,
  deleteSessionTeamBody: (count: number) =>
    `Sesi ini punya ${String(count)} anggota tim. Penugasan mereka ikut terhapus.`,
  deleteDraftTeamNote: "Penugasan tim ikut terhapus.",
  deleteSession: "Hapus",
  fieldsTitle: "Field booking",
  fieldsDescription: (service: string) =>
    `Dari layanan ${service}. Semua field tanpa (opsional) wajib diisi, juga untuk draf.`,
  fieldSelectPlaceholder: (field: string) => `Pilih ${field.toLowerCase()}`,
  // not in Pencil
  fieldYes: "Ya",
  // not in Pencil
  fieldNo: "Tidak",
  saveDraft: "Simpan draf",
  // not in Pencil
  savingDraft: "Menyimpan draf…",
  create: "Buat proyek",
  creating: "Membuat proyek…",
  sessionDialogTitle: "Tambah sesi",
  sessionEditTitle: "Ubah sesi",
  sessionDialogDescription: "Sesi disimpan bersama proyek.",
  sessionName: "Nama sesi",
  sessionNamePlaceholder: "Contoh: Akad, Resepsi, Foto keluarga",
  sessionDate: "Tanggal",
  sessionDatePlaceholder: "Pilih tanggal",
  sessionStart: "Jam mulai",
  sessionEnd: "Jam selesai",
  sessionLocation: "Lokasi",
  sessionLocationPlaceholder: "Alamat atau nama tempat",
  sessionCancel: "Batal",
  sessionSave: "Tambah sesi",
  sessionSaveEdit: "Simpan",
  serverErrorTitle: "Perubahan belum tersimpan",
  serverErrorBody: "Terjadi kendala di server. Isian formulirmu masih ada.",
  retry: "Coba lagi",
  toastCreatedTitle: "Proyek dibuat",
  toastCreatedBody: (title: string) => `${title} sudah Dibooking.`,
  toastDraftSavedTitle: "Draf disimpan",
  // not in Pencil
  toastDraftSavedBody: (title: string) => `${title} tersimpan sebagai draf.`,
  infoTitle: "Info",
  infoClient: "Klien",
  infoService: "Layanan",
  infoPrice: "Harga sepakat",
  infoNotes: "Catatan internal",
  emptyValue: "—",
  packageDescriptionDetailDesktop: (service: string) =>
    `Disalin dari ${service}. Bisa diubah sampai pemotretan dimulai.`,
  packageDescriptionDetailMobile: "Bisa diubah sampai pemotretan dimulai.",
  scheduleDescriptionDetailDesktop: "Sesi pemotretan, urut tanggal.",
  scheduleDescriptionDetailMobile: "Urut tanggal.",
  scheduleDetailEmptyBody: "Tambahkan minimal satu sesi sebelum konfirmasi booking.",
  fieldsDescriptionDetailDesktop: (service: string) =>
    `Disalin dari ${service} saat proyek dibuat.`,
  fieldsDescriptionDetailMobile: (service: string) => `Disalin dari ${service}.`,
  lockedDescription: "Terkunci sejak pemotretan dimulai.",
  cancelledDescription: "Proyek dibatalkan, tidak bisa diubah.",
  cancelledTitle: "Proyek dibatalkan",
  cancelledBy: (name: string, date: string) => `Dibatalkan oleh ${name} pada ${date}.`,
  // not in Pencil
  cancelledAnonymous: (date: string) => `Dibatalkan pada ${date}.`,
  cancelledReason: (reason: string) => `Alasan: ${reason}.`,
  metaNoSchedule: "Belum ada jadwal",
  metaNext: "Sesi berikutnya",
  metaLast: "Sesi terakhir",
  metaExtra: (count: number) => `+${String(count)} sesi`,
  stepConfirm: "Konfirmasi booking",
  stepConfirmPending: "Konfirmasi booking…",
  stepStart: "Mulai pemotretan",
  stepStartPending: "Mulai pemotretan…",
  stepFinish: "Selesai pemotretan",
  stepFinishPending: "Selesai pemotretan…",
  toastConfirmedTitle: "Booking dikonfirmasi",
  toastStartedTitle: "Pemotretan dimulai",
  toastStartedBody: "Isi paket dan harga sekarang terkunci.",
  toastFinishedTitle: "Pemotretan selesai",
  toastStaleTitle: "Status proyek sudah berubah",
  // not in Pencil
  toastStaleBody: "Halaman dimuat ulang dengan data terbaru.",
  toastSessionRequiredTitle: "Tambahkan minimal satu sesi sebelum konfirmasi booking.",
  statusDraft: "Draf",
  statusBooked: "Dibooking",
  statusShooting: "Pemotretan",
  statusPostProcessing: "Pascaproduksi",
  statusDelivered: "Terkirim",
  statusCompleted: "Selesai",
  statusCancelled: "Dibatalkan",
  listTitle: "Daftar proyek",
  listCount: (tab: "ACTIVE" | "COMPLETED" | "CANCELLED", count: number) =>
    `${String(count)} proyek ${COUNT_NOUN[tab]}`,
  clientService: (client: string, service: string) => `${client} · ${service}`,
  tabsLabel: "Status proyek",
  tabActive: "Aktif",
  tabCompleted: "Selesai",
  tabCancelled: "Dibatalkan",
  listAddDesktop: "Proyek baru",
  listAddMobile: "Baru",
  searchLabel: "Cari judul atau nama klien",
  clearSearch: "Hapus pencarian",
  searchResultCount: (count: number) => `${String(count)} proyek ditemukan`,
  columnProject: "PROYEK",
  columnEvent: "ACARA",
  columnStatus: "STATUS",
  columnActions: "Aksi",
  emptyActiveTitle: "Belum ada proyek",
  emptyActiveBody: "Buat proyek untuk mencatat klien, layanan, dan harga yang kamu sepakati.",
  emptyCompletedTitle: "Belum ada proyek yang selesai",
  emptyCompletedBody: "Proyek pindah ke sini setelah hasil akhirnya dikirim dan diselesaikan.",
  emptyCancelledTitle: "Belum ada proyek yang dibatalkan",
  emptyCancelledBody: "Proyek yang kamu batalkan muncul di sini, lengkap dengan alasannya.",
  noMatchTitle: "Tidak ada proyek yang cocok",
  noMatchBody: "Coba judul lain, atau ketik sebagian nama klien.",
  loadMore: "Muat lebih banyak",
  loadingMore: "Memuat…",
  listSubtitleDesktop: "Setiap pemotretan yang kamu pegang, dari draf sampai selesai.",
  listSubtitleMobile: "Pemotretan dari draf sampai selesai.",
  filterButton: "Filter",
  filterBadgeLabel: "aktif",
  filterTitle: "Filter proyek",
  filterDescription: (tab: "ACTIVE" | "COMPLETED" | "CANCELLED") =>
    `Berlaku untuk tab ${TAB_NAME[tab]}.`,
  filterStatus: "Status",
  filterStatusPlaceholder: "Semua status",
  filterSchedule: "Jadwal",
  filterFrom: "Dari",
  filterTo: "Sampai",
  filterDatePlaceholder: "Pilih tanggal",
  filterNoSchedule: "Sertakan proyek tanpa jadwal",
  filterService: "Layanan",
  filterServicePlaceholder: "Semua layanan",
  filterClient: "Klien",
  filterClientPlaceholder: "Semua klien",
  filterClientGroup: (count: number) => `KLIEN · ${String(count)} COCOK`,
  filterArchivedClient: (name: string) => `${name} (diarsipkan)`,
  filterToBeforeFrom: "Tanggal Sampai harus sama atau setelah Dari.",
  filterReset: "Reset",
  filterApply: "Terapkan",
  menuActions: (title: string) => `Aksi untuk ${title}`,
  menuEditInfo: "Ubah info",
  menuChat: "Chat WhatsApp",
  // not in Pencil
  menuAddNumber: "Tambah nomor WhatsApp",
  menuCancel: "Batalkan proyek",
  menuDeleteDraft: "Hapus draf",
  menuSendGroup: "KIRIM KE KLIEN",
  menuSheetMeta: (client: string, when: string, status: string) =>
    `${client} · ${when} · ${status}`,
  infoEditDesktop: "Ubah info",
  infoEditMobile: "Ubah",
  infoDialogTitle: "Ubah info",
  infoDialogDescription: "Judul, harga sepakat, dan catatan proyek.",
  infoDialogDescriptionLocked: "Judul dan catatan masih bisa diubah.",
  infoPriceLocked: "Terkunci sejak pemotretan dimulai.",
  infoSave: "Simpan",
  infoCancel: "Batal",
  // not in Pencil
  infoSavedTitle: "Info proyek disimpan",
  // not in Pencil
  infoDealLockedTitle: "Harga sudah terkunci",
  // not in Pencil
  infoCancelledTitle: "Proyek sudah dibatalkan",
  cancelDialogTitle: "Batalkan proyek?",
  // F-09 (BR-PRJ-010): the description now carries the gallery sentence (F-09 design.md › Copy).
  cancelDialogDescription:
    "Proyek pindah ke Dibatalkan dan tidak bisa diubah lagi. Galeri yang dipublikasikan ikut diarsipkan; klien tidak bisa membukanya lagi.",
  // F-09 (BR-PRJ-010): added to the cancel dialog; drawn in the F-09 copy table.
  cancelDialogGalleryNote:
    "Galeri yang dipublikasikan ikut diarsipkan; klien tidak bisa membukanya lagi.",
  cancelReasonRequiredLabel: "Alasan pembatalan",
  cancelReasonPlaceholder: "Contoh: klien membatalkan karena jadwal berubah",
  cancelBack: "Kembali",
  cancelConfirm: "Batalkan proyek",
  toastCancelledTitle: "Proyek dibatalkan",
  toastCancelledBody: (title: string) => `${title} pindah ke tab Dibatalkan.`,
  deleteDialogTitle: (title: string) => `Hapus draf “${title}”?`,
  deleteDialogBody: "Draf beserta isi paket, jadwal, dan field booking-nya dihapus permanen.",
  deleteConfirm: "Hapus draf",
  deleteCancel: "Batal",
  toastDeletedTitle: "Draf dihapus",
  toastDeletedBody: (title: string) => `${title} sudah dihapus.`,
  editSavedToast: "Perubahan disimpan",
  dealLockedTitle: "Detail paket tidak bisa diubah lagi",
  dealLockedBody: "Proyek sudah dalam pemotretan. Data terbaru sudah dimuat.",
  lastSessionToast: "Proyek yang sudah dibooking butuh minimal satu sesi.",
  itemAddTitle: "Tambah item",
  itemAddDescription: "Item hanya ditambahkan ke proyek ini.",
  itemEditTitle: (name: string) => `Ubah nilai · ${name}`,
  itemEditDescription: "Hanya berlaku untuk proyek ini. Layanan tidak berubah.",
  itemPickerLabel: "Item",
  itemPickerHelper: "Hanya item aktif yang belum ada di proyek.",
  // not in Pencil
  itemPickerPlaceholder: "Pilih item",
  quantityLabel: "Jumlah",
  unitHelper: (unit: string) => `Satuan: ${unit}`,
  rangeMin: "Minimal",
  rangeMax: "Maksimal",
  itemCancel: "Batal",
  itemAddConfirm: "Tambah item",
  itemSave: "Simpan",
  addItemDesktop: "Tambah item",
  addItemMobile: "Tambah",
  itemActions: (name: string) => `Aksi untuk item ${name}`,
  itemEditValue: "Ubah nilai",
  itemRemove: "Hapus",
  removeItemTitle: (name: string) => `Hapus ${name}?`,
  removeItemBody: "Item dihapus dari proyek ini. Layanan tidak berubah.",
  removeItemConfirm: "Hapus item",
  fieldsDialogTitle: "Ubah field booking",
  fieldsDialogDescription: "Nilai field untuk proyek ini. Nama dan jenis field tidak berubah.",
  fieldsEdit: "Ubah",
  deleteSessionTitle: (name: string) => `Hapus sesi ${name}?`,
  deleteSessionBody: "Sesi dihapus dari jadwal proyek ini.",
  deleteSessionConfirm: "Hapus sesi",
  lastSessionHint: "Proyek yang sudah dibooking butuh minimal satu sesi.",
  // not in Pencil
  sessionDialogDetailDescription: "Perubahan langsung disimpan.",
} as const;
