export const PROJECT_COPY = {
  parentLabel: "Proyek",
  createTitle: "Proyek baru",
  createSubtitle: "Pilih klien dan layanan, lalu catat apa yang kalian sepakati.",
  clientServiceTitle: "Klien & layanan",
  clientLabel: "Klien",
  clientPlaceholder: "Cari atau tambah klien",
  clientGroupLabel: (count: number) => `KLIEN · ${String(count)} COCOK`,
  clientNoMatchLabel: (query: string) => `TIDAK ADA KLIEN “${query}”`,
  clientCreateLabel: (query: string) => `Tambah klien baru “${query}”`,
  clientNoNumber: "Belum ada nomor WhatsApp",
  clientNote: (number: string, projectCount: number) =>
    `${number} · ${String(projectCount)} proyek`,
  serviceLabel: "Layanan",
  servicePlaceholder: "Pilih layanan",
  serviceHelper: (category: string, price: string) => `${category} · harga dasar ${price}`,
  packageTitle: "Isi paket",
  packageDescriptionDesktop: (service: string) =>
    `Disalin dari ${service}. Perubahan hanya berlaku untuk proyek ini.`,
  packageDescriptionMobile: (service: string) => `Dari ${service}. Hanya untuk proyek ini.`,
  packageEmptyTitle: "Layanan ini belum punya item paket",
  packageEmptyBody:
    "Tambahkan item bila perlu. Item yang kamu tambah hanya berlaku untuk proyek ini.",
  selectionEdit: "pilihan edit",
  // not in Pencil
  selectionPrint: "pilihan cetak",
  detailTitle: "Detail proyek",
  titleLabel: "Judul proyek",
  titlePlaceholderDesktop: "Terisi otomatis setelah memilih layanan",
  titlePlaceholderMobile: "Terisi setelah memilih layanan",
  titleExample: (service: string, client: string) => `Contoh: ${service} — ${client}`,
  titleHelper: "Terisi otomatis dari layanan dan klien. Bisa diubah.",
  priceLabel: "Harga sepakat",
  pricePrefix: "Rp",
  pricePlaceholder: "0",
  priceHelper: (price: string) => `Harga dasar layanan: ${price}`,
  notesLabel: "Catatan internal",
  notesPlaceholder: "Hanya kamu yang bisa melihat catatan ini.",
  scheduleTitle: "Jadwal",
  scheduleDescriptionDesktop: "Sesi pemotretan. Minimal satu sesi untuk Buat proyek.",
  scheduleDescriptionMobile: "Minimal satu sesi untuk Buat proyek.",
  addSessionDesktop: "Tambah sesi",
  addSessionMobile: "Tambah",
  scheduleEmptyTitle: "Belum ada sesi",
  scheduleEmptyBody: "Catat tanggal, jam, dan lokasi pemotretan. Draf boleh disimpan tanpa sesi.",
  sessionActions: (name: string) => `Aksi untuk sesi ${name}`,
  editSession: "Ubah",
  deleteSession: "Hapus",
  fieldsTitle: "Field booking",
  fieldsDescription: (service: string) =>
    `Dari layanan ${service}. Semua field tanpa (opsional) wajib diisi, juga untuk draf.`,
  fieldSelectPlaceholder: (field: string) => `Pilih ${field.toLowerCase()}`,
  // not in Pencil
  fieldYes: "Ya",
  // not in Pencil
  fieldNo: "Tidak",
  saveDraft: "Simpan draf",
  // not in Pencil
  savingDraft: "Menyimpan draf…",
  create: "Buat proyek",
  creating: "Membuat proyek…",
  sessionDialogTitle: "Tambah sesi",
  sessionEditTitle: "Ubah sesi",
  sessionDialogDescription: "Sesi disimpan bersama proyek.",
  sessionName: "Nama sesi",
  sessionNamePlaceholder: "Contoh: Akad, Resepsi, Foto keluarga",
  sessionDate: "Tanggal",
  sessionDatePlaceholder: "Pilih tanggal",
  sessionStart: "Jam mulai",
  sessionEnd: "Jam selesai",
  sessionLocation: "Lokasi",
  sessionLocationPlaceholder: "Alamat atau nama tempat",
  sessionCancel: "Batal",
  sessionSave: "Tambah sesi",
  sessionSaveEdit: "Simpan",
  serverErrorTitle: "Perubahan belum tersimpan",
  serverErrorBody: "Terjadi kendala di server. Isian formulirmu masih ada.",
  retry: "Coba lagi",
  toastCreatedTitle: "Proyek dibuat",
  toastCreatedBody: (title: string) => `${title} sudah Dibooking.`,
  toastDraftSavedTitle: "Draf disimpan",
  // not in Pencil
  toastDraftSavedBody: (title: string) => `${title} tersimpan sebagai draf.`,
} as const;
